development:
  adapter: postgresql
  encoding: unicode
  database: policycatalog_development
  pool: 5
  username: <%= ENV['USER'] %>
  password:
  min_messages: notice

test:
  adapter: postgresql
  encoding: unicode
  database: policycatalog_test
  pool: 5
  username: <%= ENV['USER'] %>
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: policycatalog_production
  pool: 5
  username: <%= ENV['USER'] %>
  password:
